<?php
// Do not edit this file. Generated by admin script.
// RealEstateManager Configuration file
// General Informations 
$realestatemanager_configuration['release']['version']='3.9.10 Free';
$realestatemanager_configuration['release']['date']='May 2017';
// edit house 
$realestatemanager_configuration['edithouse']['default']['lang']='';
// price settings
$realestatemanager_configuration['price']['show']='1';
$realestatemanager_configuration['price']['registrationlevel']='-2';
// auto increment for houseid, if 1 - can't add random houseid 
$realestatemanager_configuration['houseid']['auto-increment']['boolean']='1';
// review settings
$realestatemanager_configuration['reviews']['show']='1';
$realestatemanager_configuration['reviews']['registrationlevel']='-2';
// show cb_myhouse
$realestatemanager_configuration['cb_myhouse']['show']='0';
$realestatemanager_configuration['cb_myhouse']['registrationlevel']='';
// show cb_edit
$realestatemanager_configuration['cb_edit']['show']='1';
$realestatemanager_configuration['cb_edit']['registrationlevel']='-2';
// show cb_rent
$realestatemanager_configuration['cb_rent']['show']='1';
$realestatemanager_configuration['cb_rent']['registrationlevel']='-2';
// show cb_buy
$realestatemanager_configuration['cb_buy']['show']='1';
$realestatemanager_configuration['cb_buy']['registrationlevel']='-2';
// show cb_history
$realestatemanager_configuration['cb_history']['show']='1';
$realestatemanager_configuration['cb_history']['registrationlevel']='-2';
// show Location
$realestatemanager_configuration['location_tab']['show']='1';
$realestatemanager_configuration ['location_tab']['registrationlevel']='-2';
$realestatemanager_configuration['reviews_tab']['show']='1';
$realestatemanager_configuration['reviews_tab']['registrationlevel']='-2';
// rent settings
$realestatemanager_configuration['rentstatus']['show']='1';
$realestatemanager_configuration['rentrequest']['registrationlevel']='-2';
// status settings
$realestatemanager_configuration['housestatus']['show']='1';
$realestatemanager_configuration['houserequest']['registrationlevel']='-2';
// buy settings
$realestatemanager_configuration['buystatus']['show']='1';
$realestatemanager_configuration['buyrequest']['registrationlevel']='-2';
// edoc settings
$realestatemanager_configuration['edocs']['allow']='1';
$realestatemanager_configuration['edocs']['show']='1';
$realestatemanager_configuration['edocs']['registrationlevel']='-2';
$realestatemanager_configuration['edocs']['location']='/components/com_realestatemanager/edocs/';
// video and track
$realestatemanager_configuration['videos_tracks']['show']='1';
$realestatemanager_configuration['allowed_exts_video']='mp4,ogv,webm';
$realestatemanager_configuration['allowed_exts_track']='vtt';
$realestatemanager_configuration['videos']['location']='/components/com_realestatemanager/media/video/';
$realestatemanager_configuration['tracks']['location']='/components/com_realestatemanager/media/track/';
// debuging
$realestatemanager_configuration['debug']='';
$realestatemanager_configuration['page']['items']='10';
// foto size
$realestatemanager_configuration['thumb_param']['show']= '1';
$realestatemanager_configuration['foto']['high']= '170';
$realestatemanager_configuration['foto']['width']= '250';
$realestatemanager_configuration['fotomain']['high']= '440';
$realestatemanager_configuration['fotomain']['width']= '808';
$realestatemanager_configuration['fotoupload']['high']= '600';
$realestatemanager_configuration['fotoupload']['width']= '1400';
$realestatemanager_configuration['fotogallery']['high']= '100';
$realestatemanager_configuration['fotogallery']['width']= '100';
$realestatemanager_configuration['fotocategory']['high']= '200';
$realestatemanager_configuration['fotocategory']['width']= '265';
$realestatemanager_configuration['fotogal']['high']= '100';
$realestatemanager_configuration['fotogal']['width']= '100';
$realestatemanager_configuration['license']['show']='1';
$realestatemanager_configuration['license']['text']= '<p>Untitled document</p>
<p>License Text</p>';
$realestatemanager_configuration['api_key']='AIzaSyD4ZY-54e-nzN0-KejXHkUh-D7bbexDMKk';
//user manager
$realestatemanager_configuration['user_manager_rem']['-2']['count_homes']='10';
$realestatemanager_configuration['user_manager_rem']['-2']['count_foto']='10';
$realestatemanager_configuration['user_manager_rem']['29']['count_homes']='5';
$realestatemanager_configuration['user_manager_rem']['29']['count_foto']='';
$realestatemanager_configuration['user_manager_rem']['18']['count_homes']='5';
$realestatemanager_configuration['user_manager_rem']['18']['count_foto']='';
$realestatemanager_configuration['user_manager_rem']['19']['count_homes']='5';
$realestatemanager_configuration['user_manager_rem']['19']['count_foto']='';
$realestatemanager_configuration['user_manager_rem']['20']['count_homes']='5';
$realestatemanager_configuration['user_manager_rem']['20']['count_foto']='';
$realestatemanager_configuration['user_manager_rem']['21']['count_homes']='5';
$realestatemanager_configuration['user_manager_rem']['21']['count_foto']='';
$realestatemanager_configuration['user_manager_rem']['32']['count_homes']='5';
$realestatemanager_configuration['user_manager_rem']['32']['count_foto']='';
$realestatemanager_configuration['user_manager_rem']['30']['count_homes']='5';
$realestatemanager_configuration['user_manager_rem']['30']['count_foto']='';
$realestatemanager_configuration['user_manager_rem']['23']['count_homes']='5';
$realestatemanager_configuration['user_manager_rem']['23']['count_foto']='';
$realestatemanager_configuration['user_manager_rem']['24']['count_homes']='5';
$realestatemanager_configuration['user_manager_rem']['24']['count_foto']='';
$realestatemanager_configuration['user_manager_rem']['25']['count_homes']='5';
$realestatemanager_configuration['user_manager_rem']['25']['count_foto']='';
$realestatemanager_configuration['user_manager_rem']['']['count_homes']='0';
$realestatemanager_configuration['user_manager_rem']['']['count_foto']='';
$realestatemanager_configuration['user_manager_rem']['1']['count_homes']='10';
$realestatemanager_configuration['user_manager_rem']['1']['count_foto']='10';
$realestatemanager_configuration['user_manager_rem']['6']['count_homes']='10';
$realestatemanager_configuration['user_manager_rem']['6']['count_foto']='10';
$realestatemanager_configuration['user_manager_rem']['7']['count_homes']='10';
$realestatemanager_configuration['user_manager_rem']['7']['count_foto']='10';
$realestatemanager_configuration['user_manager_rem']['2']['count_homes']='10';
$realestatemanager_configuration['user_manager_rem']['2']['count_foto']='10';
$realestatemanager_configuration['user_manager_rem']['3']['count_homes']='10';
$realestatemanager_configuration['user_manager_rem']['3']['count_foto']='10';
$realestatemanager_configuration['user_manager_rem']['4']['count_homes']='10';
$realestatemanager_configuration['user_manager_rem']['4']['count_foto']='10';
$realestatemanager_configuration['user_manager_rem']['5']['count_homes']='10';
$realestatemanager_configuration['user_manager_rem']['5']['count_foto']='10';
$realestatemanager_configuration['user_manager_rem']['8']['count_homes']='10';
$realestatemanager_configuration['user_manager_rem']['8']['count_foto']='10';
$realestatemanager_configuration['user_manager_rem']['10']['count_homes']='10';
$realestatemanager_configuration['user_manager_rem']['10']['count_foto']='10';
$realestatemanager_configuration['user_manager_rem']['12']['count_homes']='10';
$realestatemanager_configuration['user_manager_rem']['12']['count_foto']='10';
$realestatemanager_configuration['user_manager_rem']['9']['count_homes']='10';
$realestatemanager_configuration['user_manager_rem']['9']['count_foto']='10';
$realestatemanager_configuration['user_manager_rem']['11']['count_homes']='11';
$realestatemanager_configuration['user_manager_rem']['11']['count_foto']='10';
$realestatemanager_configuration['cancel_url']='';
$realestatemanager_configuration['success_url']='';
$realestatemanager_configuration['paypal_real_or_test']['show']='0';
// paypal buy settings
$realestatemanager_configuration['special_price']['show']='1';
$realestatemanager_configuration['paypal_buy_status']['show']='1';
$realestatemanager_configuration['paypal_buy']['registrationlevel']='-2';
$realestatemanager_configuration['paypal_buy_status_sale']['show']='1';
$realestatemanager_configuration['paypal_buy_sale']['registrationlevel']='-2';
$realestatemanager_configuration['approve_on_add']['show']='1';
$realestatemanager_configuration['approve_on_add']['registrationlevel']='-2';
$realestatemanager_configuration['publish_on_add']['show']='1';
$realestatemanager_configuration['publish_on_add']['registrationlevel']='-2';
$realestatemanager_configuration['searchlayout_map']['show']='1';
$realestatemanager_configuration['searchlayout_map']['registrationlevel']='-2';
$realestatemanager_configuration['searchlayout_orderby']['show']='0';
$realestatemanager_configuration['searchlayout_orderby']['registrationlevel']='-2';
$realestatemanager_configuration['search_option']['show']='1';
$realestatemanager_configuration['search_option']['registrationlevel']='-2';
// show in category picture
$realestatemanager_configuration['cat_pic']['show']='1';
// show subcategory
$realestatemanager_configuration['subcategory']['show']='1';
//view_house
$realestatemanager_configuration['view_house']='';
//show location map
$realestatemanager_configuration['location_map']='1';
$realestatemanager_configuration['calendar']['show']='1';
$realestatemanager_configuration['calendarlist']['show']='';
$realestatemanager_configuration['calendarlist']['registrationlevel']='-2';
$realestatemanager_configuration['rent_form']='0';
$realestatemanager_configuration['buy_form']='0';
//manager_feature_category
$realestatemanager_configuration['manager_feature_category']='1';
//sale_separator
$realestatemanager_configuration['sale_separator']='1';
//extra1
$realestatemanager_configuration['extra1']='0';
//extra2
$realestatemanager_configuration['extra2']='0';
//extra3
$realestatemanager_configuration['extra3']='0';
//extra4
$realestatemanager_configuration['extra4']='0';
//extra5
$realestatemanager_configuration['extra5']='0';
//extra6
$realestatemanager_configuration['extra6']='0';
//extra7
$realestatemanager_configuration['extra7']='0';
//extra8
$realestatemanager_configuration['extra8']='0';
//extra9
$realestatemanager_configuration['extra9']='0';
//extra10
$realestatemanager_configuration['extra10']='0';
$realestatemanager_configuration['featuredmanager']['placeholder']='Interior, Exterior, Specific';
$realestatemanager_configuration['currency']='USD=1;EUR=0.89;CAD=1.2;';
$realestatemanager_configuration['allowed_exts']='';
$realestatemanager_configuration['allowed_exts_img']='jpeg,jpg,png,gif';
$realestatemanager_configuration['price_format']='.';
// 1 - affter 0 - beffore
$realestatemanager_configuration['price_unit_show']='1';
$realestatemanager_configuration['date_format']='%Y-%m-%d';
$realestatemanager_configuration['datetime_format']='%H:%i:%s';
$realestatemanager_configuration['plugin_name_select']='';
?>